### ISSUE TITLE
compiling error for arduino due

### ISSUE THREAD

**Issue by peiyzhou** [bolderflight/Eigen#2]
Hello,

Thanks first for all your shared libraries and they are really useful.
Currently, I am compiling the Eigen library for Arduino Due, with Arduino IDE 1.85. When I run the example code, the following errors shows:

Arduino: 1.8.5 (Windows 10), Board: "Arduino Due (Programming Port)"

In file included from \arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1\arm-none-eabi\include\c++\4.8.3\random:39:0,

                 from \arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1\arm-none-eabi\include\c++\4.8.3\bits\stl_algo.h:65,

                 from \arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1\arm-none-eabi\include\c++\4.8.3\algorithm:62,

                 from \Arduino\libraries\Eigen/Eigen/Core:269,

                 from \Arduino\libraries\Eigen/Eigen.h:61,

                 from \Arduino\libraries\Eigen\examples\eigenTest\eigenTest.ino:5:

\arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1\arm-none-eabi\include\c++\4.8.3\cstdio:122:11: error: '::printf' has not been declared

   using ::printf;

           ^

exit status 1
Error compiling for board Arduino Due (Programming Port).

How can I fix this problem? thanks.

**Comment by flybrianfly** [comment]
The GCC version for the Arduino Due core is a little different than the Teensy or Ladybug cores, which this has been tested working on. I downloaded the Arduino Due core and was able to reproduce your error. The solution I have is to modify the following file:
``` 
\arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1\arm-none-eabi\include\c++\4.8.3\random
```
By commenting out:
```
#include <cstdio>
```
It's on line 39. The version of GCC that Teensy and Ladybug are using does not use this include. After making this modification, the example compiled fine with no errors or warnings.

**Comment by peiyzhou** [comment]
thank you! It works now.
